# Generated by Django 4.2 on 2023-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get2talk', '0002_alter_lesson_student_alter_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='supervisor_comment',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
